name: Feature Branch Workflow

on:
  push:
    branches: [ 'feature/*' ]
  pull_request:
    branches: [ develop ]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Install CMake
      run: sudo apt-get install -y cmake
      
    - name: Build and Test
      run: |
        mkdir build
        cd build
        cmake ..
        make
        ./run_tests